//
// Created by Chris on 2023-01-13.
//

#ifndef VOYAGEUR_CONSTANTS_H
#define VOYAGEUR_CONSTANTS_H
const int RESOURCE_ORDER_NONE = 0;
const int RESOURCE_ORDER_NAME = 1;
const int RESOURCE_ORDER_AMOUNT = 2;
const int RESOURCE_ORDER_HARDNESS = 3;

#endif //VOYAGEUR_CONSTANTS_H
